# Generated by Django 4.2.4 on 2023-09-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Middle_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Phone_Name', models.CharField(max_length=15)),
                ('College_Name', models.CharField(max_length=100)),
                ('Home_Address', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=10)),
                ('Area_of_Intrest', models.CharField(max_length=100)),
            ],
        ),
    ]
